[app]

title = Dino Stick
package.name = dinostick
package.domain = org.dinostick

source.dir = .
source.include_exts = py,png,jpg,kv,atlas,wav,ogg,ttf
source.include_patterns = assets/*,assets/*/*

version = 0.1.0

# pyjnius is needed for the WifiManager.MulticastLock that makes UDP
# discovery work on Android at all (see net/discovery.py).
requirements = python3,kivy==2.3.1,pyjnius

# All four are generated by tools/make_branding.py from the game's own data --
# the dino comes out of SKINS, the backdrop is a crop of the season the game
# opens on -- so the launcher icon can never drift from what the game actually
# looks like. Re-run that script after changing either.
#
# icon.filename is the legacy icon, used by Android 7 and older launchers.
# Android 8+ takes the two adaptive layers instead and masks them into whatever
# shape the device uses; a single flat icon gets letterboxed into a white blob
# on those launchers, which is why both exist.
#
# The adaptive keys are spelled "icon.adaptive_foreground.filename", not the
# "icon.adaptive_icon_foreground" you will find in most snippets online, and
# buildozer only understands them from 1.6.0 -- on 1.5.0 they are accepted in
# silence and thrown away. It also needs BOTH or it uses neither. Hence the
# version pin in .github/workflows/android.yml.
icon.filename = %(source.dir)s/assets/icon.png
icon.adaptive_foreground.filename = %(source.dir)s/assets/icon_fg.png
icon.adaptive_background.filename = %(source.dir)s/assets/icon_bg.png

# The splash the user stares at while Python and Kivy boot -- several seconds
# on a cold start. presplash_color fills the screen AROUND the square image,
# which on a landscape phone is two tall bars down the sides, so it is sampled
# from the image's own left/right edge columns rather than being a guess. It
# used to be COLOR_BG; against the painted seasons that flashed pale grey
# before the first dark frame landed.
presplash.filename = %(source.dir)s/assets/presplash.png
android.presplash_color = #48705A

orientation = landscape
fullscreen = 1

# INTERNET                     - TCP game traffic + UDP discovery
# ACCESS_NETWORK_STATE         - detect whether we are on a network
# ACCESS_WIFI_STATE            - read Wi-Fi info
# CHANGE_WIFI_MULTICAST_STATE  - REQUIRED to hold a MulticastLock; without it
#                                Android silently drops broadcast packets and
#                                discovery finds nothing.
android.permissions = INTERNET, ACCESS_NETWORK_STATE, ACCESS_WIFI_STATE, CHANGE_WIFI_MULTICAST_STATE

android.api = 34
android.minapi = 24
android.archs = arm64-v8a, armeabi-v7a

android.allow_backup = True

# Raw TCP/UDP sockets on the LAN are NOT affected by Android's cleartext-HTTP
# block (that applies to HttpURLConnection/OkHttp), so no network security
# config is needed. Nothing here ever speaks HTTP.

# Answers the SDK licence prompts, so a first build does not stall waiting for
# a keypress it never shows you.
android.accept_sdk_license = True

[buildozer]

log_level = 2
warn_on_root = 1
